apache:
  image: "httpd:2.4"
  ports:
  - "80:80"
  volumes:
  - "./httpd/htdocs:/usr/local/apache2/htdocs:ro"
  - "./httpd/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro"
  - "./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
  links:
  - "jenkins:jenkins"

#nginx:
#  image: "nginx:1.9.9"
#  ports:
#  - "80:80"
#  volumes:
#  - "./htdocs:/usr/share/nginx/html:ro"

jenkins:
  image: "jenkins:1.625.3"
  ports:
  - "8080:8080"
  - "50000:50000"
  environment:
  - "JENKINS_OPTS=--prefix=/jenkins" 
#goServer:
#  image: "gocd/gocd-server:latest"
#  ports:
#  - "8153:8153"
#  container_name: go-server

#nexus:
#  image: "sonatype/nexus:latest"
#  ports:
#  - "8081:8081"

#artifcatory:
#  image: "mattgruter/artifactory:latest"

#sonarqube:
#  image: "sonarqube:latest"
#  ports:
#  - "9000:9000"
#  - "9092:9092"
